spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card
    username: postgres
    password: Aliyev@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
